updates:
  - directory: /
    ignore:
      - dependency-name: serialize-error

    package-ecosystem: npm
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
version: 2
