jobs:
  dependabot:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - id: metadata
        name: Dependabot metadata
        uses: dependabot/fetch-metadata@v1.6.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_URL: ${{github.event.pull_request.html_url}}
        name: Approve a PR
        run: gh pr review --approve "$PR_URL"
name: Dependabot auto-approve
on: pull_request_target

permissions:
  pull-requests: write
